/*
 * robot.h
 *
 *  Created on: 2017/03/07
 *      Author: tattaka
 */

#ifndef USERINC_ROBOT_H_
#define USERINC_ROBOT_H_

#include "stm32f4xx_hal.h"

//misc module
#define HELLOWORLD()	printf("Hello world!\n")

//GPIO module
#define DEBUG_LED1_SET()	HAL_GPIO_WritePin (GPIOB, GPIO_PIN_6, GPIO_PIN_SET)
#define DEBUG_LED2_SET()	HAL_GPIO_WritePin (GPIOB, GPIO_PIN_7, GPIO_PIN_SET)
#define DEBUG_LED3_SET()	HAL_GPIO_WritePin (GPIOB, GPIO_PIN_8, GPIO_PIN_SET)
#define DEBUG_LED4_SET()	HAL_GPIO_WritePin (GPIOB, GPIO_PIN_9, GPIO_PIN_SET)
#define DEBUG_LED5_SET()	HAL_GPIO_WritePin (GPIOE, GPIO_PIN_0, GPIO_PIN_SET)
#define DEBUG_LED6_SET()	HAL_GPIO_WritePin (GPIOE, GPIO_PIN_1, GPIO_PIN_SET)

#define DEBUG_LED1_RESET()	HAL_GPIO_WritePin (GPIOB, GPIO_PIN_6, GPIO_PIN_RESET)
#define DEBUG_LED2_RESET()	HAL_GPIO_WritePin (GPIOB, GPIO_PIN_7, GPIO_PIN_RESET)
#define DEBUG_LED3_RESET()	HAL_GPIO_WritePin (GPIOB, GPIO_PIN_8, GPIO_PIN_RESET)
#define DEBUG_LED4_RESET()	HAL_GPIO_WritePin (GPIOB, GPIO_PIN_9, GPIO_PIN_RESET)
#define DEBUG_LED5_RESET()	HAL_GPIO_WritePin (GPIOE, GPIO_PIN_0, GPIO_PIN_RESET)
#define DEBUG_LED6_RESET()	HAL_GPIO_WritePin (GPIOE, GPIO_PIN_1, GPIO_PIN_RESET)

#define MPU6500_CS_SET()		HAL_GPIO_WritePin (GPIOA, GPIO_PIN_15, GPIO_PIN_SET)
#define MPU6500_CS_RESET()		HAL_GPIO_WritePin (GPIOA, GPIO_PIN_15, GPIO_PIN_RESET)

#define RAM_CS_SET()		HAL_GPIO_WritePin (GPIOD, GPIO_PIN_7, GPIO_PIN_SET)
#define RAM_CS_RESET()		HAL_GPIO_WritePin (GPIOD, GPIO_PIN_7, GPIO_PIN_RESET)

#define LINEADC_CS_SET()		HAL_GPIO_WritePin (GPIOB, GPIO_PIN_12, GPIO_PIN_SET)
#define LINEADC_CS_RESET()		HAL_GPIO_WritePin (GPIOB, GPIO_PIN_12, GPIO_PIN_RESET)

#define SENSOR_LED1_SET()	HAL_GPIO_WritePin (GPIOB, GPIO_PIN_11, GPIO_PIN_SET)
#define SENSOR_LED2_SET()	HAL_GPIO_WritePin (GPIOB, GPIO_PIN_10, GPIO_PIN_SET)
#define SENSOR_LED3_SET()	HAL_GPIO_WritePin (GPIOE, GPIO_PIN_15, GPIO_PIN_SET)
#define SENSOR_LED4_SET()	HAL_GPIO_WritePin (GPIOE, GPIO_PIN_7, GPIO_PIN_SET)
#define SENSOR_LED5_SET()	HAL_GPIO_WritePin (GPIOB, GPIO_PIN_1, GPIO_PIN_SET)
#define SENSOR_LED6_SET()	HAL_GPIO_WritePin (GPIOB, GPIO_PIN_0, GPIO_PIN_SET)

#define SENSOR_LED1_RESET()	HAL_GPIO_WritePin (GPIOB, GPIO_PIN_11, GPIO_PIN_RESET)
#define SENSOR_LED2_RESET()	HAL_GPIO_WritePin (GPIOB, GPIO_PIN_10, GPIO_PIN_RESET)
#define SENSOR_LED3_RESET()	HAL_GPIO_WritePin (GPIOE, GPIO_PIN_15, GPIO_PIN_RESET)
#define SENSOR_LED4_RESET()	HAL_GPIO_WritePin (GPIOE, GPIO_PIN_7, GPIO_PIN_RESET)
#define SENSOR_LED5_RESET()	HAL_GPIO_WritePin (GPIOB, GPIO_PIN_1, GPIO_PIN_RESET)
#define SENSOR_LED6_RESET()	HAL_GPIO_WritePin (GPIOB, GPIO_PIN_0, GPIO_PIN_RESET)

#define RMOTER1_GPIO_SET()	HAL_GPIO_WritePin (GPIOE, GPIO_PIN_11, GPIO_PIN_SET)
#define RMOTER2_GPIO_SET()	HAL_GPIO_WritePin (GPIOE, GPIO_PIN_10, GPIO_PIN_SET)
#define LMOTER1_GPIO_SET()	HAL_GPIO_WritePin (GPIOE, GPIO_PIN_12, GPIO_PIN_SET)
#define LMOTER2_GPIO_SET()	HAL_GPIO_WritePin (GPIOE, GPIO_PIN_13, GPIO_PIN_SET)

#define RMOTER1_GPIO_RESET()	HAL_GPIO_WritePin (GPIOE, GPIO_PIN_11, GPIO_PIN_RESET)
#define RMOTER2_GPIO_RESET()	HAL_GPIO_WritePin (GPIOE, GPIO_PIN_10, GPIO_PIN_RESET)
#define LMOTER1_GPIO_RESET()	HAL_GPIO_WritePin (GPIOE, GPIO_PIN_12, GPIO_PIN_RESET)
#define LMOTER2_GPIO_RESET()	HAL_GPIO_WritePin (GPIOE, GPIO_PIN_13, GPIO_PIN_RESET)

#define STBY_GPIO_SET()		HAL_GPIO_WritePin (GPIOE, GPIO_PIN_8, GPIO_PIN_SET)
#define STBY_GPIO_RESET()	HAL_GPIO_WritePin (GPIOE, GPIO_PIN_8, GPIO_PIN_RESET)

#define RGB_RED_RESET() HAL_GPIO_WritePin (GPIOD, GPIO_PIN_8, GPIO_PIN_SET)
#define RGB_BLUE_RESET() HAL_GPIO_WritePin (GPIOD, GPIO_PIN_9, GPIO_PIN_SET)
#define RGB_GREEN_RESET() HAL_GPIO_WritePin (GPIOD, GPIO_PIN_10, GPIO_PIN_SET)
#define RGB_RED_SET() HAL_GPIO_WritePin (GPIOD, GPIO_PIN_8, GPIO_PIN_RESET)
#define RGB_BLUE_SET() HAL_GPIO_WritePin (GPIOD, GPIO_PIN_9, GPIO_PIN_RESET)
#define RGB_GREEN_SET() HAL_GPIO_WritePin (GPIOD, GPIO_PIN_10, GPIO_PIN_RESET)


//TIM module
#define MUSIC_TIM	htim9
#define MUSIC_CHAN	TIM_CHANNEL_2

#define ENCODER_L_TIM	htim4
#define ENCODER_R_TIM	htim2
#define ENCODER_L_CNT	TIM4->CNT
#define ENCODER_R_CNT	TIM2->CNT

#define MOTER_TIM		htim1
#define MOTER_L_CHAN	TIM_CHANNEL_4
#define MOTER_R_CHAN	TIM_CHANNEL_1

//ADC module
#define SENSOR_ADC	hadc1
#define SENSOR1_CHAN	ADC_CHANNEL_15
#define SENSOR2_CHAN	ADC_CHANNEL_14
#define SENSOR3_CHAN	ADC_CHANNEL_7
#define SENSOR4_CHAN	ADC_CHANNEL_6
#define SENSOR5_CHAN	ADC_CHANNEL_5
#define SENSOR6_CHAN	ADC_CHANNEL_4
#define SENSOR_NUM		6

#define VAT_ADC	hadc2

//SPI module
#define MPU6500_SPI	hspi1
#define MRAM_SPI hspi3

#endif /* USERINC_ROBOT_H_ */
